[adam]
[adam.nvidia]
aot = "benchmarks/hecbench/cuda/adam"
proteus = "benchmarks/hecbench/cuda/adam"
jitify = "benchmarks/hecbench/cuda-jitify/adam"
[adam.amd]
aot = "benchmarks/hecbench/hip/adam"
proteus = "benchmarks/hecbench/hip/adam"
[adam.inputs]
default = "160000 1600 1000"

[feynman-kac]
[feynman-kac.nvidia]
aot = "benchmarks/hecbench/cuda/feynman-kac"
proteus = "benchmarks/hecbench/cuda/feynman-kac"
jitify = "benchmarks/hecbench/cuda-jitify/feynman-kac"
[feynman-kac.amd]
aot = "benchmarks/hecbench/hip/feynman-kac"
proteus = "benchmarks/hecbench/hip/feynman-kac"
[feynman-kac.inputs]
default = "1"

[lulesh]
[lulesh.nvidia]
aot = "benchmarks/hecbench/cuda/LULESH"
proteus = "benchmarks/hecbench/cuda/LULESH"
jitify = "benchmarks/hecbench/cuda-jitify/LULESH"
[lulesh.amd]
aot = "benchmarks/hecbench/hip/LULESH"
proteus = "benchmarks/hecbench/hip/LULESH"
[lulesh.inputs]
default = "-s 128"

[rsbench]
[rsbench.nvidia]
aot = "benchmarks/hecbench/cuda/rsbench"
proteus = "benchmarks/hecbench/cuda/rsbench"
jitify = "benchmarks/hecbench/cuda-jitify/rsbench"
[rsbench.amd]
aot = "benchmarks/hecbench/hip/rsbench"
proteus = "benchmarks/hecbench/hip/rsbench"
[rsbench.inputs]
default = "-s large -m event"

[sw4ck]
[sw4ck.nvidia]
aot = "benchmarks/hecbench/cuda/sw4ck"
proteus = "benchmarks/hecbench/cuda/sw4ck"
jitify = "benchmarks/hecbench/cuda-jitify/sw4ck"
[sw4ck.amd]
aot = "benchmarks/hecbench/hip/sw4ck"
proteus = "benchmarks/hecbench/hip/sw4ck"
[sw4ck.inputs]
default = "sw4ck.in 100"

[wsm5]
[wsm5.nvidia]
aot = "benchmarks/hecbench/cuda/wsm5"
proteus = "benchmarks/hecbench/cuda/wsm5"
jitify = "benchmarks/hecbench/cuda-jitify/wsm5"
[wsm5.amd]
aot = "benchmarks/hecbench/hip/wsm5"
proteus = "benchmarks/hecbench/hip/wsm5"
[wsm5.inputs]
default = "10"
