[LBANN]
[LBANN.config]
exe = "install/bin/lbann"
path = "benchmarks/lbann-bench"
build_once = true

[LBANN.config.build.amd.aot]
path = "benchmarks/lbann-bench/build-aot"
[LBANN.config.build.amd.proteus]
path = "benchmarks/lbann-bench/build-proteus"

[LBANN.config.build.amd]
command = ["""
           export LBANN_PATH=$(realpath ../../lbann)
           /usr/workspace/proteus/lbann/setup-amd.sh
           """,
           """
           source /usr/workspace/proteus/lbann/prefix-path-amd.sh
           ninja
           """]

[LBANN.layernorm]
args = "--disable_distconv --prototext=layernorm.prototext"
[LBANN.layernorm.inputs]
default = ""
