[RAJAPerf]
[RAJAPerf.config]
path = "benchmarks/RAJAPerf"
exe = "build/bin/raja-perf.exe"
build_once = true
[RAJAPerf.config.build.nvidia.clean]
command = "rm -rf build"
[RAJAPerf.config.build.nvidia.proteus]
command = ["""
            cmake       -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=${CC} \
                        -DCMAKE_CXX_COMPILER=${CXX} \
                        -DRAJA_ENABLE_EXTERNAL_ROCPRIM=Off \
                        -DPROTEUS_INSTALL_DIR=${PROTEUS_PATH} \
                        -DENABLE_CUDA=on \
                        -DENABLE_CLANG_CUDA=on \
                        -DBLT_CLANG_CUDA_ARCH=sm_70 \
                        -DCMAKE_CUDA_ARCHITECTURES=70 \
                        -DCMAKE_CUDA_COMPILER=${CXX} \
                        -DENABLE_JIT=On \
                        -DBLT_CXX_STD=c++17 \
                        -B build \
            """, "cmake --build build --target raja-perf.exe -- -j"]
[RAJAPerf.config.build.nvidia.aot]
command = ["""
            cmake       -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=${CC} \
                        -DCMAKE_CXX_COMPILER=${CXX} \
                        -DRAJA_ENABLE_EXTERNAL_ROCPRIM=Off \
                        -DPROTEUS_INSTALL_DIR=${PROTEUS_PATH} \
                        -DENABLE_CUDA=on \
                        -DENABLE_CLANG_CUDA=on \
                        -DBLT_CLANG_CUDA_ARCH=sm_70 \
                        -DCMAKE_CUDA_ARCHITECTURES=70 \
                        -DCMAKE_CUDA_COMPILER=${CXX} \
                        -DENABLE_JIT=Off \
                        -DBLT_CXX_STD=c++17 \
                        -B build \
            """, "cmake --build build --target raja-perf.exe -- -j"]
[RAJAPerf.config.build.amd.clean]
command = "rm -rf build"
[RAJAPerf.config.build.amd.aot]
command = [
    """
            cmake       -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=${CC} \
                        -DCMAKE_CXX_COMPILER=${CXX} \
                        -DRAJA_ENABLE_EXTERNAL_ROCPRIM=Off \
                        -DPROTEUS_INSTALL_DIR=${PROTEUS_PATH} \
                        -DENABLE_HIP=on \
                        -DCMAKE_HIP_ARCHITECTURES=gfx90a  \
                        -DGPU_TARGETS=gfx90a \
                        -DENABLE_JIT=Off \
                        -B build \
                        """,
    "cmake --build build --target raja-perf.exe -- -j ",
]
[RAJAPerf.config.build.amd.proteus]
command = [
    """
            cmake       -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=${CC} \
                        -DCMAKE_CXX_COMPILER=${CXX} \
                        -DRAJA_ENABLE_EXTERNAL_ROCPRIM=Off \
                        -DPROTEUS_INSTALL_DIR=${PROTEUS_PATH} \
                        -DENABLE_HIP=on \
                        -DCMAKE_POSITION_INDEPENDENT_CODE=On \
                        -DPOSITION_INDEPENDENT_CODE=On \
                        -DCMAKE_HIP_ARCHITECTURES=gfx90a  \
                        -DGPU_TARGETS=gfx90a \
                        -DENABLE_JIT=On \
                        -DBLT_CXX_STD=c++17 \
                        -B build \
                        """,
    "cmake --build build --target raja-perf.exe -- -j ",
]
[RAJAPerf.config.nvidia.aot]
args = "--variants RAJA_CUDA --disable-warmup "
[RAJAPerf.config.nvidia.proteus]
args = "--variants RAJA_CUDA --disable-warmup "
[RAJAPerf.config.amd.aot]
args = "--variants RAJA_HIP --disable-warmup"
[RAJAPerf.config.amd.proteus]
args = "--variants RAJA_HIP --disable-warmup"

[RAJAPerf.ATOMIC]
args = "-k ATOMIC"
[RAJAPerf.ATOMIC.inputs]
default = ""

# Set repfact larger for histogram because of tendency to pagefault on CUDA
[RAJAPerf.HISTOGRAM]
args = "-k HISTOGRAM"
[RAJAPerf.HISTOGRAM.inputs]
default = " --tunings atomic_direct_256 --repfact 3"

[RAJAPerf.MEMCPY]
args = "-k MEMCPY"
[RAJAPerf.MEMCPY.inputs]
default = ""

[RAJAPerf.MEMSET]
args = "-k MEMSET"
[RAJAPerf.MEMSET.inputs]
default = ""

[RAJAPerf.REDUCE_SUM]
args = "-k REDUCE_SUM"
[RAJAPerf.REDUCE_SUM.inputs]
default = " --tunings blkdev_direct_256"

[RAJAPerf.DEL_DOT_VEC_2D]
args = "-k DEL_DOT_VEC_2D"
[RAJAPerf.DEL_DOT_VEC_2D.inputs]
default = ""

[RAJAPerf.EDGE3D]
args = "-k EDGE3D"
[RAJAPerf.EDGE3D.inputs]
default = ""

[RAJAPerf.ENERGY]
args = "-k ENERGY"
[RAJAPerf.ENERGY.inputs]
default = ""

[RAJAPerf.FIR]
args = "-k FIR"
[RAJAPerf.FIR.inputs]
default = ""

[RAJAPerf.MATVEC_3D_STENCIL]
args = "-k MATVEC_3D_STENCIL"
[RAJAPerf.MATVEC_3D_STENCIL.inputs]
default = ""

[RAJAPerf.NODAL_ACCUMULATION_3D]
args = "-k NODAL_ACCUMULATION_3D"
[RAJAPerf.NODAL_ACCUMULATION_3D.inputs]
default = ""

[RAJAPerf.PRESSURE]
args = "-k PRESSURE"
[RAJAPerf.PRESSURE.inputs]
default = ""

[RAJAPerf.VOL3D]
args = "-k VOL3D"
[RAJAPerf.VOL3D.inputs]
default = ""

[RAJAPerf.ZONAL_ACCUMULATION_3D]
args = "-k ZONAL_ACCUMULATION_3D"
[RAJAPerf.ZONAL_ACCUMULATION_3D.inputs]
default = ""

[RAJAPerf.ARRAY_OF_PTRS]
args = "-k ARRAY_OF_PTRS"
[RAJAPerf.ARRAY_OF_PTRS.inputs]
default = ""

[RAJAPerf.COPY8]
args = "-k COPY8"
[RAJAPerf.COPY8.inputs]
default = ""

[RAJAPerf.DAXPY]
args = "-k DAXPY"
[RAJAPerf.DAXPY.inputs]
default = ""

[RAJAPerf.DAXPY_ATOMIC]
args = "-k DAXPY_ATOMIC"
[RAJAPerf.DAXPY_ATOMIC.inputs]
default = ""

[RAJAPerf.IF_QUAD]
args = "-k IF_QUAD"
[RAJAPerf.IF_QUAD.inputs]
default = ""

[RAJAPerf.INIT3]
args = "-k INIT3"
[RAJAPerf.INIT3.inputs]
default = ""

[RAJAPerf.INIT_VIEW1D]
args = "-k INIT_VIEW1D"
[RAJAPerf.INIT_VIEW1D.inputs]
default = ""

[RAJAPerf.INIT_VIEW1D_OFFSET]
args = "-k INIT_VIEW1D_OFFSET"
[RAJAPerf.INIT_VIEW1D_OFFSET.inputs]
default = ""

[RAJAPerf.INDEXLIST_3LOOP]
args = "-k INDEXLIST_3LOOP"
[RAJAPerf.INDEXLIST_3LOOP.inputs]
default = ""

# No RAJA HIP/ RAJA CUDA implementations exists
#[RAJAPerf.INDEXLIST]
#args = "-k INDEXLIST"
#[RAJAPerf.INDEXLIST.inputs]
#default = ""

[RAJAPerf.LTIMES]
args = "-k LTIMES"
[RAJAPerf.LTIMES.inputs]
default = ""

[RAJAPerf.LTIMES_NOVIEW]
args = "-k LTIMES_NOVIEW"
[RAJAPerf.LTIMES_NOVIEW.inputs]
default = ""

[RAJAPerf.MULADDSUB]
args = "-k MULADDSUB"
[RAJAPerf.MULADDSUB.inputs]
default = ""

[RAJAPerf.MUL]
args = "-k MUL"
[RAJAPerf.MUL.inputs]
default = ""

[RAJAPerf.MULTI_REDUCE]
args = "-k MULTI_REDUCE"
[RAJAPerf.MULTI_REDUCE.inputs]
default = " --tunings atomic_direct_256 --repfact 3"

[RAJAPerf.NESTED_INIT]
args = "-k NESTED_INIT"
[RAJAPerf.NESTED_INIT.inputs]
default = ""

# Make the default size smaller to avoid slow atomic ops
[RAJAPerf.PI_ATOMIC]
args = "-k PI_ATOMIC"
[RAJAPerf.PI_ATOMIC.inputs]
default = ""

# Set repfact larger for histogram because of tendency to pagefault on CUDA
[RAJAPerf.PI_REDUCE]
args = "-k PI_REDUCE"
[RAJAPerf.PI_REDUCE.inputs]
default = " --tunings blkdev_direct_256"

[RAJAPerf.REDUCE3_INT]
args = "-k REDUCE3_INT"
[RAJAPerf.REDUCE3_INT.inputs]
default = " --tunings blkdev_direct_256"

[RAJAPerf.REDUCE_STRUCT]
args = "-k REDUCE_STRUCT"
[RAJAPerf.REDUCE_STRUCT.inputs]
default = " --tunings blkdev_direct_256"

[RAJAPerf.TRAP_INT]
args = "-k TRAP_INT"
[RAJAPerf.TRAP_INT.inputs]
default = " --tunings blkdev_direct_256"

# These studies are not considered for P3HPC 25 because the resulting times
# have too high of a spread from the noise introduced from communication.
#[RAJAPerf.HALO_PACKING]
#args = "-k HALO_PACKING"
#[RAJAPerf.HALO_PACKING.inputs]
#default = ""
#
#[RAJAPerf.HALO_PACKING_FUSED]
#args = "-k HALO_PACKING_FUSED"
#[RAJAPerf.HALO_PACKING_FUSED.inputs]
#default = ""
#
#[RAJAPerf.HALO_EXCHANGE]
#args = "-k HALO_EXCHANGE"
#[RAJAPerf.HALO_EXCHANGE.inputs]
#default = ""
#
#[RAJAPerf.HALO_EXCHANGE_FUSED]
#args = "-k HALO_EXCHANGE_FUSED"
#[RAJAPerf.HALO_EXCHANGE_FUSED.inputs]
#default = ""
#
#[RAJAPerf.HALO_SENDRECV]
#args = "-k HALO_SENDRECV"
#[RAJAPerf.HALO_SENDRECV.inputs]
#default = ""

[RAJAPerf.DIFF_PREDICT]
args = "-k DIFF_PREDICT"
[RAJAPerf.DIFF_PREDICT.inputs]
default = ""

[RAJAPerf.EOS]
args = "-k EOS"
[RAJAPerf.EOS.inputs]
default = ""

[RAJAPerf.FIRST_DIFF]
args = "-k FIRST_DIFF"
[RAJAPerf.FIRST_DIFF.inputs]
default = ""

[RAJAPerf.FIRST_MIN]
args = "-k FIRST_MIN"
[RAJAPerf.FIRST_MIN.inputs]
default = " --tunings blkdev_direct_256"

[RAJAPerf.FIRST_SUM]
args = "-k FIRST_SUM"
[RAJAPerf.FIRST_SUM.inputs]
default = ""

[RAJAPerf.GEN_LIN_RECUR]
args = "-k GEN_LIN_RECUR"
[RAJAPerf.GEN_LIN_RECUR.inputs]
default = ""

[RAJAPerf.HYDRO_1D]
args = "-k HYDRO_1D"
[RAJAPerf.HYDRO_1D.inputs]
default = ""

[RAJAPerf.HYDRO_2D]
args = "-k HYDRO_2D"
[RAJAPerf.HYDRO_2D.inputs]
default = ""

[RAJAPerf.INT_PREDICT]
args = "-k INT_PREDICT"
[RAJAPerf.INT_PREDICT.inputs]
default = ""

[RAJAPerf.PLANCKIAN]
args = "-k PLANCKIAN"
[RAJAPerf.PLANCKIAN.inputs]
default = ""

[RAJAPerf.TRIDIAG_ELIM]
args = "-k TRIDIAG_ELIM"
[RAJAPerf.TRIDIAG_ELIM.inputs]
default = ""

[RAJAPerf.ADD]
args = "-k ADD"
[RAJAPerf.ADD.inputs]
default = ""

[RAJAPerf.CONVECTION3DPA]
args = "-k CONVECTION3DPA"
[RAJAPerf.CONVECTION3DPA.inputs]
default = ""

[RAJAPerf.DIFFUSION3DPA]
args = "-k DIFFUSION3DPA"
[RAJAPerf.DIFFUSION3DPA.inputs]
default = ""

# Defaul reps is too low, only 1
[RAJAPerf.MASS3DEA]
args = "-k MASS3DEA"
[RAJAPerf.MASS3DEA.inputs]
default = " --repfact 100 "

[RAJAPerf.MASS3DPA]
args = "-k MASS3DPA"
[RAJAPerf.MASS3DPA.inputs]
default = ""

[RAJAPerf.MAT_MAT_SHARED]
args = "-k MAT_MAT_SHARED"
[RAJAPerf.MAT_MAT_SHARED.inputs]
default = ""

# default reps too low, only two
[RAJAPerf.2MM]
args = "-k 2MM"
[RAJAPerf.2MM.inputs]
default = " --repfact 5 "

# default reps too low, only two
[RAJAPerf.3MM]
args = "-k 3MM"
[RAJAPerf.3MM.inputs]
default = "--repfact 5 "

[RAJAPerf.ADI]
args = "-k ADI"
[RAJAPerf.ADI.inputs]
default = "--repfact 3 "

[RAJAPerf.ATAX]
args = "-k ATAX"
[RAJAPerf.ATAX.inputs]
default = ""

[RAJAPerf.FDTD_2D]
args = "-k FDTD_2D"
[RAJAPerf.FDTD_2D.inputs]
default = ""

[RAJAPerf.FLOYD_WARSHALL]
args = "-k FLOYD_WARSHALL"
[RAJAPerf.FLOYD_WARSHALL.inputs]
default = ""

[RAJAPerf.GEMM]
args = "-k GEMM"
[RAJAPerf.GEMM.inputs]
default = ""

[RAJAPerf.GEMVER]
args = "-k GEMVER"
[RAJAPerf.GEMVER.inputs]
default = ""

[RAJAPerf.GESUMMV]
args = "-k GESUMMV"
[RAJAPerf.GESUMMV.inputs]
default = ""

[RAJAPerf.HEAT_3D]
args = "-k HEAT_3D"
[RAJAPerf.HEAT_3D.inputs]
default = ""

[RAJAPerf.JACOBI_1D]
args = "-k JACOBI_1D"
[RAJAPerf.JACOBI_1D.inputs]
default = ""

[RAJAPerf.JACOBI_2D]
args = "-k JACOBI_2D"
[RAJAPerf.JACOBI_2D.inputs]
default = ""

[RAJAPerf.MVT]
args = "-k MVT"
[RAJAPerf.MVT.inputs]
default = ""

[RAJAPerf.TRIAD]
args = "-k TRIAD"
[RAJAPerf.TRIAD.inputs]
default = ""

[RAJAPerf.DOT]
args = "-k DOT"
[RAJAPerf.DOT.inputs]
default = ""

[RAJAPerf.COPY]
args = "-k COPY"
[RAJAPerf.COPY.inputs]
default = ""
