[[proteus]]
profmode = "profiler"
[[proteus.env]]
PROTEUS_USE_STORED_CACHE = "0"
PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "1"
PROTEUS_SPECIALIZE_ARGS = "1"
PROTEUS_SPECIALIZE_DIMS = "1"
[[proteus.env]]
PROTEUS_USE_STORED_CACHE = "0"
PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "0"
PROTEUS_SPECIALIZE_ARGS = "0"
PROTEUS_SPECIALIZE_DIMS = "0"
[[proteus.env]]
PROTEUS_USE_STORED_CACHE = "0"
PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "1"
PROTEUS_SPECIALIZE_ARGS = "0"
PROTEUS_SPECIALIZE_DIMS = "0"
[[proteus.env]]
PROTEUS_USE_STORED_CACHE = "0"
PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "0"
PROTEUS_SPECIALIZE_ARGS = "1"
PROTEUS_SPECIALIZE_DIMS = "0"
[[proteus.env]]
PROTEUS_USE_STORED_CACHE = "0"
PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "0"
PROTEUS_SPECIALIZE_ARGS = "0"
PROTEUS_SPECIALIZE_DIMS = "1"
